import { AdminConfig, FormFieldConfig, PayScaleGrade, AdhocReliefRule } from '../types';
import { REGIONS_DISTRICTS_MAP, TALUKAS_MAP } from './regionsData';

export const DEFAULT_FORM_FIELDS: FormFieldConfig[] = [
  {
    id: 'f1',
    key: 'name',
    label: '1. Name of Employee',
    category: 'personal',
    placeholder: 'e.g. Muhammad Ali Ansari',
    type: 'text',
    enabled: true,
    required: true,
    order: 1,
    helpText: 'Full official name matching CNIC and Appointment Order',
  },
  {
    id: 'f2',
    key: 'fatherName',
    label: '2. Name of Father (S/o, D/o, W/o)',
    category: 'personal',
    placeholder: 'e.g. Ghulam Muhammad',
    type: 'text',
    enabled: true,
    required: true,
    order: 2,
    helpText: "Father's or husband's name",
  },
  {
    id: 'f3',
    key: 'designation',
    label: '3. Designation',
    category: 'personal',
    type: 'select',
    options: [
      { label: 'PST (Primary School Teacher)', value: 'PST' },
      { label: 'JEST (Junior Elementary School Teacher)', value: 'JEST' },
      { label: 'ECT (Early Childhood Teacher)', value: 'ECT' },
      { label: 'HST (High School Teacher)', value: 'HST' },
      { label: 'SLT (Sindhi Language Teacher)', value: 'SLT' },
      { label: 'OT (Oriental Teacher)', value: 'OT' },
      { label: 'AT (Arabic Teacher)', value: 'AT' },
      { label: 'PET (Physical Education Teacher)', value: 'PET' },
      { label: 'Junior Clerk', value: 'Junior Clerk' },
      { label: 'Senior Clerk', value: 'Senior Clerk' },
      { label: 'Head Master / Mistress', value: 'Head Master' },
    ],
    enabled: true,
    required: true,
    order: 3,
  },
  {
    id: 'f4',
    key: 'bps',
    label: '4. BPS Scale Grade',
    category: 'personal',
    type: 'select',
    options: [
      { label: 'BPS-09', value: 9 },
      { label: 'BPS-11', value: 11 },
      { label: 'BPS-12', value: 12 },
      { label: 'BPS-14 (Standard PST / JEST)', value: 14 },
      { label: 'BPS-15', value: 15 },
      { label: 'BPS-16 (HST / HM)', value: 16 },
      { label: 'BPS-17 (Subject Specialist / SS)', value: 17 },
      { label: 'BPS-18', value: 18 },
    ],
    enabled: true,
    required: true,
    order: 4,
  },
  {
    id: 'f5',
    key: 'cnic',
    label: '5. CNIC # (Identity Card)',
    category: 'personal',
    placeholder: '41302-1803974-3',
    type: 'text',
    enabled: true,
    required: true,
    order: 5,
    helpText: '13-digit Computerized National ID Card format',
  },
  {
    id: 'f6',
    key: 'personnelId',
    label: '6. Personnel ID (P# / SAP No)',
    category: 'personal',
    placeholder: 'e.g. 10823456',
    type: 'text',
    enabled: true,
    required: true,
    order: 6,
    helpText: '8-digit Sindh AG SAP Personnel number',
  },
  {
    id: 'f7',
    key: 'region',
    label: '7. Region of Posting',
    category: 'posting',
    type: 'select',
    options: [
      { label: 'Hyderabad Region', value: 'Hyderabad_Region' },
      { label: 'Karachi Region', value: 'Karachi_Region' },
      { label: 'Sukkur Region', value: 'Sukkur_Region' },
      { label: 'Larkana Region', value: 'Larkana_Region' },
      { label: 'Mirpurkhas Region', value: 'Mirpurkhas_Region' },
      { label: 'Shaheed Benazirabad Region', value: 'Shaheed_Benazirabad_Region' },
    ],
    enabled: true,
    required: true,
    order: 7,
  },
  {
    id: 'f8',
    key: 'district',
    label: '8. District',
    category: 'posting',
    type: 'select',
    enabled: true,
    required: true,
    order: 8,
  },
  {
    id: 'f9',
    key: 'taluka',
    label: '9. Taluka / Tehsil',
    category: 'posting',
    type: 'select',
    enabled: true,
    required: true,
    order: 9,
  },
  {
    id: 'f10',
    key: 'appointmentDate',
    label: '10. Date of Joining / Appointment',
    category: 'period',
    type: 'date',
    enabled: true,
    required: true,
    order: 10,
    helpText: 'Start date from which arrears start',
  },
  {
    id: 'f11',
    key: 'arrearUptoDate',
    label: '11. Arrear Required Upto (End Date)',
    category: 'period',
    type: 'date',
    enabled: true,
    required: true,
    order: 11,
    helpText: 'Last date of unpaid period',
  },
  {
    id: 'f12',
    key: 'isIncrementAdded',
    label: '12. Add Annual Increment on Dec 1st?',
    category: 'rates',
    type: 'boolean',
    enabled: true,
    required: false,
    order: 12,
    helpText: 'Adds annual scale increment for service crossing December 1st',
  },
  {
    id: 'f13',
    key: 'isDisability',
    label: '13. Disability Allowance (Special Conveyance)?',
    category: 'rates',
    type: 'boolean',
    enabled: true,
    required: false,
    order: 13,
  },
  {
    id: 'f14',
    key: 'houseRentType',
    label: '14. House Rent Category',
    category: 'rates',
    type: 'select',
    options: [
      { label: 'Urban (Rs. 3,321 / month for BPS-14)', value: 'Urban' },
      { label: 'Rural (Rs. 2,253 / month for BPS-14)', value: 'Rural' },
    ],
    enabled: true,
    required: true,
    order: 14,
  },
  {
    id: 'f15',
    key: 'isTeachingAllowance',
    label: 'Teaching / B.Ed Allowance (Rs. 1,000/mo)?',
    category: 'rates',
    type: 'boolean',
    enabled: true,
    required: false,
    order: 15,
    helpText: 'Professional Teaching / B.Ed qualification allowance of Rs. 1,000/month for PSTs/JESTs',
  },
  {
    id: 'f16',
    key: 'schoolName',
    label: '16. School / Institute Name',
    category: 'posting',
    placeholder: 'e.g. Govt. Boys Primary School Qasimabad',
    type: 'text',
    enabled: true,
    required: true,
    order: 16,
  },
  {
    id: 'f17',
    key: 'semisCode',
    label: '17. SEMIS Code',
    category: 'posting',
    placeholder: 'e.g. 403020123',
    type: 'text',
    enabled: true,
    required: true,
    order: 17,
  },
  {
    id: 'f18',
    key: 'ddoFirstLine',
    label: '18. DDO Office Title (Line 1)',
    category: 'ddo',
    placeholder: 'Taluka Education Officer (Male)',
    type: 'text',
    enabled: true,
    required: true,
    order: 18,
  },
  {
    id: 'f19',
    key: 'ddoSecondLine',
    label: '19. DDO Office Jurisdiction (Line 2)',
    category: 'ddo',
    placeholder: 'Elementary, Secondary & Higher Secondary',
    type: 'text',
    enabled: true,
    required: true,
    order: 19,
  },
  {
    id: 'f20',
    key: 'ddoCode',
    label: '20. DDO Code',
    category: 'ddo',
    placeholder: 'HB-0123',
    type: 'text',
    enabled: true,
    required: true,
    order: 20,
  },
  {
    id: 'f21',
    key: 'costCenter',
    label: '21. Cost Center / Section',
    category: 'ddo',
    placeholder: 'GA-III',
    type: 'text',
    enabled: true,
    required: true,
    order: 21,
  },
];

export const DEFAULT_PAY_SCALES: PayScaleGrade[] = [
  {
    bps: 9,
    name: 'BPS-09',
    initialBasicPay: 15400,
    annualIncrement: 1040,
    maximumBasicPay: 36200,
    houseRentUrban: 2310,
    houseRentRural: 1540,
    conveyanceAllowance: 1932,
    medicalAllowance: 1375,
    gpfRate: 2600,
    bfRate: 230,
    giRate: 310,
  },
  {
    bps: 11,
    name: 'BPS-11',
    initialBasicPay: 18050,
    annualIncrement: 1250,
    maximumBasicPay: 43050,
    houseRentUrban: 2708,
    houseRentRural: 1805,
    conveyanceAllowance: 2160,
    medicalAllowance: 1375,
    gpfRate: 3100,
    bfRate: 270,
    giRate: 370,
  },
  {
    bps: 12,
    name: 'BPS-12',
    initialBasicPay: 19500,
    annualIncrement: 1420,
    maximumBasicPay: 47900,
    houseRentUrban: 2925,
    houseRentRural: 1950,
    conveyanceAllowance: 2160,
    medicalAllowance: 1375,
    gpfRate: 3400,
    bfRate: 295,
    giRate: 400,
  },
  {
    bps: 14,
    name: 'BPS-14 (PST / JEST Standard)',
    initialBasicPay: 22530,
    annualIncrement: 1740,
    maximumBasicPay: 57330,
    houseRentUrban: 3321,
    houseRentRural: 2253,
    conveyanceAllowance: 2856,
    medicalAllowance: 1375,
    gpfRate: 3900,
    bfRate: 338,
    giRate: 464,
  },
  {
    bps: 15,
    name: 'BPS-15',
    initialBasicPay: 24340,
    annualIncrement: 1960,
    maximumBasicPay: 63540,
    houseRentUrban: 3651,
    houseRentRural: 2434,
    conveyanceAllowance: 2856,
    medicalAllowance: 1375,
    gpfRate: 4200,
    bfRate: 365,
    giRate: 500,
  },
  {
    bps: 16,
    name: 'BPS-16 (HST / HM)',
    initialBasicPay: 28070,
    annualIncrement: 2260,
    maximumBasicPay: 73270,
    houseRentUrban: 4211,
    houseRentRural: 2807,
    conveyanceAllowance: 5000,
    medicalAllowance: 1375,
    gpfRate: 4900,
    bfRate: 420,
    giRate: 580,
  },
  {
    bps: 17,
    name: 'BPS-17 (Subject Specialist / Lecturer)',
    initialBasicPay: 45070,
    annualIncrement: 3420,
    maximumBasicPay: 113470,
    houseRentUrban: 6761,
    houseRentRural: 4507,
    conveyanceAllowance: 5000,
    medicalAllowance: 1375,
    gpfRate: 7800,
    bfRate: 675,
    giRate: 930,
  },
  {
    bps: 18,
    name: 'BPS-18 (Assistant Professor / Senior HM)',
    initialBasicPay: 56880,
    annualIncrement: 4260,
    maximumBasicPay: 142080,
    houseRentUrban: 8532,
    houseRentRural: 5688,
    conveyanceAllowance: 5000,
    medicalAllowance: 1375,
    gpfRate: 9800,
    bfRate: 850,
    giRate: 1170,
  },
];

export const DEFAULT_ADHOC_RULES: AdhocReliefRule[] = [
  {
    id: 'adhoc-2017',
    year: 2017,
    name: 'Adhoc Relief 2017 (10%)',
    shortCode: 'adhoc2017',
    percentage: 10,
    calculationBase: 'fixed',
    effectiveFrom: '2017-07',
    fixedMonthlyAmount: 0,
    enabled: false,
    notes: 'Sindh Govt Finance Department 2017',
  },
  {
    id: 'adhoc-2018',
    year: 2018,
    name: 'Adhoc Relief 2018 (10%)',
    shortCode: 'adhoc2018',
    percentage: 10,
    calculationBase: 'fixed',
    effectiveFrom: '2018-07',
    fixedMonthlyAmount: 0,
    enabled: false,
  },
  {
    id: 'adhoc-2019',
    year: 2019,
    name: 'Adhoc Relief 2019 (15%)',
    shortCode: 'adhoc2019',
    percentage: 15,
    calculationBase: 'fixed',
    effectiveFrom: '2019-07',
    fixedMonthlyAmount: 0,
    enabled: false,
  },
  {
    id: 'adhoc-2020',
    year: 2020,
    name: 'Adhoc Relief 2020 (10%)',
    shortCode: 'adhoc2020',
    percentage: 10,
    calculationBase: 'fixed',
    effectiveFrom: '2020-07',
    fixedMonthlyAmount: 0,
    enabled: false,
  },
  {
    id: 'adhoc-2021',
    year: 2021,
    name: 'Adhoc Relief 2021 (20%)',
    shortCode: 'adhoc2021',
    percentage: 20,
    calculationBase: 'fixed',
    effectiveFrom: '2021-07',
    fixedMonthlyAmount: 0,
    enabled: false,
  },
  {
    id: 'adhoc-2022',
    year: 2022,
    name: 'Adhoc Relief 2022 (15%)',
    shortCode: 'adhoc2022',
    percentage: 15,
    calculationBase: 'initialBasic2022',
    effectiveFrom: '2022-07',
    fixedMonthlyAmount: 2277,
    enabled: true,
    notes: '15% on Basic Pay of 2022 (Rs. 2,277 for BPS-14)',
  },
  {
    id: 'diff-2022',
    year: 2022,
    name: 'Differential Allowance 2022 (34.35%)',
    shortCode: 'diff2022',
    percentage: 34.35,
    calculationBase: 'initialBasic2022',
    effectiveFrom: '2022-07',
    fixedMonthlyAmount: 5237,
    enabled: true,
    notes: '34.35% for Sindh Provincial Employees (Rs. 5,237 for BPS-14)',
  },
  {
    id: 'adhoc-2023',
    year: 2023,
    name: 'Adhoc Relief 2023 (35%)',
    shortCode: 'adhoc2023',
    percentage: 35,
    calculationBase: 'runningBasic',
    effectiveFrom: '2023-07',
    fixedMonthlyAmount: 7885,
    enabled: true,
    notes: '35% of Basic Pay (Rs. 7,885 for BPS-14)',
  },
  {
    id: 'adhoc-2024',
    year: 2024,
    name: 'Adhoc Relief 2024 (25%)',
    shortCode: 'adhoc2024',
    percentage: 25,
    calculationBase: 'runningBasic',
    effectiveFrom: '2024-07',
    fixedMonthlyAmount: 5632,
    enabled: true,
    notes: '25% on Running Basic (Rs. 5,632 for BPS-14)',
  },
  {
    id: 'adhoc-2025',
    year: 2025,
    name: 'Adhoc Relief 2025 (12%)',
    shortCode: 'adhoc2025',
    percentage: 12,
    calculationBase: 'runningBasic',
    effectiveFrom: '2025-07',
    fixedMonthlyAmount: 2703,
    enabled: true,
    notes: '12% effective 1st July 2025 (Rs. 2,703 for BPS-14)',
  },
  {
    id: 'adhoc-2026',
    year: 2026,
    name: 'Adhoc Relief 2026 (7%)',
    shortCode: 'adhoc2026',
    percentage: 7,
    calculationBase: 'runningBasic',
    effectiveFrom: '2026-07',
    fixedMonthlyAmount: 1577,
    enabled: true,
    notes: '7% effective 1st July 2026 under new Pay Revision',
  },
  {
    id: 'diff-2026',
    year: 2026,
    name: 'Differential Allowance 2026 (2%)',
    shortCode: 'diff2026',
    percentage: 2,
    calculationBase: 'runningBasic',
    effectiveFrom: '2026-07',
    fixedMonthlyAmount: 450,
    enabled: true,
    notes: '2% Special Relief Allowance (Rs. 450 for BPS-14)',
  },
];

export const DEFAULT_ADMIN_CONFIG: AdminConfig = {
  adminPasswordHash: 'sindh2026', // simple credential for admin mode
  portalTitle: 'Sindh Education & Finance Portal',
  portalSubtitle: 'Official Salary Arrears, Payroll & Allowance Processing System',
  footerNotice: 'Government of Sindh — School Education & Literacy Department / District Accounts Offices',
  defaultAppointmentDate: '2025-06-24',
  defaultArrearUptoDate: '2026-07-31',
  fields: DEFAULT_FORM_FIELDS,
  payScales: DEFAULT_PAY_SCALES,
  adhocRules: DEFAULT_ADHOC_RULES,
  customAllowances: [],
  customDeductions: [],
  regionsDistricts: REGIONS_DISTRICTS_MAP,
  talukas: TALUKAS_MAP,
  ddoMasters: [
    {
      code: 'HB0379',
      firstLine: 'Taluka Education Officer',
      secondLine: 'Male Primary Hyderabad Rural',
      costCenter: 'HB0379',
      district: 'Hyderabad',
    },
    {
      code: 'HB-0123',
      firstLine: 'Taluka Education Officer (Male)',
      secondLine: 'Elementary, Secondary & Higher Secondary',
      costCenter: 'GA-III',
      district: 'Hyderabad',
    },
    {
      code: 'HB-0456',
      firstLine: 'District Education Officer (Primary)',
      secondLine: 'School Education & Literacy Department',
      costCenter: 'GA-I',
      district: 'Hyderabad',
    },
    {
      code: 'KQ-0789',
      firstLine: 'Taluka Education Officer (Female)',
      secondLine: 'Karachi Central District',
      costCenter: 'KC-02',
      district: 'Karachi Central',
    },
    {
      code: 'SK-0321',
      firstLine: 'Taluka Education Officer (Primary)',
      secondLine: 'Sukkur City & Rural',
      costCenter: 'SK-01',
      district: 'Sukkur',
    },
  ],
};
